### ISSUE TITLE
Stuck at ImportError: No module named backports

### ISSUE THREAD

**Issue by averyfreeman** [macq/spec2deb#3]
Not real familiar with python3, trying to run on Ubuntu 20.04.  
Installed backports.lzma via pip3 

Error message when running spec2deb:

`Traceback (most recent call last):
  File "/home/avery/bin/spec2deb", line 24, in <module>
    from backports import lzma
ImportError: No module named backports`

ldd shows this for lzma.cpython-38-x86_64-linux-gnu.so:

`ldd /home/avery/.local/lib/python3.8/site-packages/backports/lzma/_lzma.cpython-38-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffe611f2000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb7abea4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb7abcb2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb7abc8f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb7abedc000)`

**Comment by chrismaes87** [comment]
If you look at the code: https://github.com/macq/spec2deb/blob/master/src/spec2deb/spec2deb.py#L21
you can see that I try importing `lzma` first. The `backports.lzma` is meant for python2. for Python3 you should not need to install lzma since it is part of python3: https://docs.python.org/3/library/lzma.html.

Try starting python3 and running `import lzma`. That should work out of the box.

**Comment by averyfreeman** [comment]
OK thank you :)
